version: "3.8"
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: slackbot_postgres
    environment:
      POSTGRES_USER: slackuser
      POSTGRES_PASSWORD: slackpass
      POSTGRES_DB: slackdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: slackbot_opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true  # 인증 없이 OpenSearch 접근 가능
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"  # OpenSearch API
      - "9600:9600"  # Performance Analyzer
    volumes:
      - osdata:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: slackbot_dashboards
    ports:
      - "5601:5601"  # 웹 UI 포트
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true  # 보안 인증 끄기 (필수!)
    depends_on:
      - opensearch

volumes:
  pgdata:
  osdata:
